/*
    Interface module which parallelizes the serial ADC line-in data
    and crosses between the sampling clk and the ADC capture clock domains

    Author: Kevin Johnson
    Ported to SV and modified by: Jacob Dudik
*/

module adc_interface #(
        parameter ADC_WIDTH = 16
    )(
        input logic i_adc_wclk, // audio CODEC LR clock | PIN_AH29
        input logic i_adc_bclk, // audio CODEC bitstream clock | PIN_AF30
        input logic i_adc_dat,  // audio CODEC ADC data | PIN_AJ29
        input logic i_poll_clk,  // clock that FACE will use to poll the ADC

        output logic [ADC_WIDTH-1:0] o_adc_dat,
        output logic o_sample_rdy
    );

    logic [ADC_WIDTH-1:0] shifted_data; // Shift register output
    logic [ADC_WIDTH-1:0] buffer_data;  // Output buffer
    logic write_req, read_req;      // FIFO control signals
    logic rdempty, rdempty_delay;   // New data flags
    int bit_count;  // Counter for number of bits shifted in

    // Shift register to parallelize the data from the ADC
    // THIS IS 16 BITS LONG AND WILL NEED TO BE ADJUSTED IF ADC_WIDHT != 16
    adc_shiftreg serialize 
    (
        .clock(i_adc_bclk),
        .shiftin(i_adc_dat),
        .q(shifted_data)
    );

    // Dual-clock FIFO to ensure timing saftey between ADC and FACE clock domains
    adc_fifo fifo
    (
        .data(shifted_data), // Data input from ADC
        .rdclk(i_poll_clk),  // Read clock (sync to i_poll_clk)
        .rdreq(read_req),    // Read request (generated by FIFO cntrl logic)
        .wrclk(i_adc_bclk),  // Write clock (sync to i_adc_bclk)
        .wrreq(write_req),   // Write request (generated by FIFO cntrl logic)
        .q(o_adc_dat),       // Data output from FIFO
        .rdempty(rdempty)    // Empty flag
    );


    assign read_req = !rdempty; // Whenever new data is available, pull it out of the FIFO

    // Indicate new data after data updates
    always_ff @(negedge i_poll_clk) begin
        /*
            Using the falling edge keeps changes away from sample times
        in your peripheral.  This isn't a good practice because it can
        cut your effective max frequency in half, but this isn't a
        bleeding-edge system and this is much easier than trying to
        design around timing constraints.
        */

        // Indicate data new after pulled from FIFO.
        rdempty_delay <= !rdempty;
        o_sample_rdy <= rdempty_delay;
    end

    // Track number of bits coming in and latch into FIFO when needed
    always_ff @(posedge i_adc_bclk) begin
        if (i_adc_wclk == '1) bit_count <= ADC_WIDTH; // Start counting when word clock is high
        else if (bit_count != 0) bit_count <= bit_count - 1;
        
        if (bit_count == 1) write_req <= '1; // Write data to FIFO after ADC_WIDTH bits have been shifted in
        else write_req <= '0;
    end
endmodule