complex_magnitude_sim/complex_magnitude_memoryC0_uid193_sqrtTables_lutmem.hex
complex_magnitude_sim/complex_magnitude_memoryC1_uid196_sqrtTables_lutmem.hex
complex_magnitude_sim/complex_magnitude_memoryC2_uid199_sqrtTables_lutmem.hex
complex_magnitude_sim/complex_magnitude.vo
